parameters:
- name: apiFileName
  displayName: API File Name
  type: string
- name: artifactName
  displayName: Artifact Name
  type: string
- name: azureSubscription
  displayName: Azure Subscription
  type: string
- name: appName
  displayName: Web App Name
  type: string
- name: resourceGroupName
  displayName: Resource Group Name
  type: string
- name: reportName
  displayName: Report Name
  type: string

jobs:
- job: 'buildjob'
  pool: 
    vmImage: 'windows-latest'
  steps:
  - checkout: self

  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appName: ${{ parameters.appName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appSettings: |
        [
           {
            "name": "IpRateLimit__RateLimitPerMinute",
            "value": "60000",
            "slotSetting": false
           },
           {
            "name": "IpRateLimit__RateLimitPerSecond",
            "value": "10000",
            "slotSetting": false
           }
        ]