parameters:
- name: apiFileName
  displayName: API File Name
  type: string
- name: artifactName
  displayName: Artifact Name
  type: string
- name: azureSubscription
  displayName: Azure Subscription
  type: string
- name: appName
  displayName: Web App Name
  type: string
- name: resourceGroupName
  displayName: Resource Group Name
  type: string
- name: reportName
  displayName: Report Name
  type: string

jobs:
- job: 'buildjob'
  pool: 
    vmImage: 'windows-latest'
  steps:
  - checkout: self

  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appName: ${{ parameters.appName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appSettings: |
        [
           {
            "name": "IpRateLimit__RateLimitPerMinute",
            "value": "60000",
            "slotSetting": false
           },
           {
            "name": "IpRateLimit__RateLimitPerSecond",
            "value": "10000",
            "slotSetting": false
           }
        ]

  - task: AzureAppServiceManage@0
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      Action: 'Restart Azure App Service'
      WebAppName: ${{ parameters.appName }}

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host("Sleep 2 minutes")
        Start-Sleep -Seconds 120

  - task: k6-load-test@0
    inputs:
      filename: ${{ parameters.apiFileName }}

  - task: AzureAppServiceSettings@1
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      appName: ${{ parameters.appName }}
      resourceGroupName: ${{ parameters.resourceGroupName }}
      appSettings: |
        [
           {
            "name": "IpRateLimit__RateLimitPerMinute",
            "value": "6000",
            "slotSetting": false